#whitelist_rules:
excluded: # paths to ignore during linting.
  - Carthage
  
disabled_rules:
    - implicit_getter
    - line_length
    - trailing_whitespace
    - trailing_newline

identifier_name:
    excluded:
        - to
        - id
        - db
        - ok
        
file_length:
    warning: 500
    error: 600
    
type_body_length:
    warning: 300
    error: 400